name: lightgcn-env
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - pytorch
  - tqdm
  - cudatoolkit=10.2 # CUDA 버전은 시스템에 맞게 조정
  - mlflow
  - pip
  - pip:
      - torch
